version: '3.8'

services:
  taskflow-app:
    build: .
    image: taskflow:latest
    ports:
      - "${PORT}:${PORT}"
    # Docker Compose va charger dynamiquement le bon fichier .env passé en variable
    env_file:
      - ${ENV_FILE:-dev.env}
    restart: always